[package]
name = "validate_cube"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "validate_cube"
path = "src/main.rs"

[dependencies]
common-types = { path = "../crates/common-types" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
env_logger = "0.10"