[package]
name = "common-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
bevy = { version = "0.12", optional = true }
uniffi = { version = "0.28", optional = true }

[features]
bevy = ["dep:bevy"]
ffi = ["uniffi"]