[package]
name = "m2-quant"
version = "0.1.0"
edition = "2021"

[dependencies]
common-types = { path = "../common-types" }
image = "0.25.0"
nalgebra = "0.33.0"
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"

[dev-dependencies]
serde_json = "1.0"