name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
    
    - name: Run Unit Tests
      run: ./gradlew test
      
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: app/build/reports/tests/

  instrumented-test:
    runs-on: macos-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Download APK
      uses: actions/download-artifact@v3
      with:
        name: app-debug
        path: ./
    
    - name: Start Android Emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        arch: x86_64
        profile: Nexus 6
        avd-name: test
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
        disable-animations: true
        script: |
          # Install APK
          adb install app-debug.apk
          
          # Grant permissions
          adb shell pm grant com.rgbagif.debug android.permission.CAMERA
          
          # Start app
          adb shell am start -n com.rgbagif.debug/com.rgbagif.MainActivity
          
          # Wait for app to initialize
          sleep 5
          
          # Run milestone tests
          ./scripts/grab_logs.sh
          
          # Check M1 logs
          M1_COUNT=$(wc -l < m1.log)
          if [ $M1_COUNT -lt 50 ]; then
            echo "M1 test failed: only $M1_COUNT log entries"
            exit 1
          fi
          
          echo "Tests passed!"

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Run Lint
      run: ./gradlew lint
    
    - name: Upload Lint Results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: lint-results
        path: app/build/reports/lint-results-debug.html